name: CI
on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.HONEYCOMB_APIKEY }}
          dataset: go-tfe-run
          job-status: ${{ job.status }}

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - run: go get -v -t -d ./...
      - run: go test ./...
      - run: go build -v .
      - run: go vet
      - run: test -z $(gofmt -l .)
